version: '3.0'
services:
  eosio-contract-api-filler:
    container_name: eosio-contract-api-filler
    build: .
    command: yarn run start:filler
    restart: on-failure
    depends_on:
      - eosio-contract-api-postgres
      - eosio-contract-api-redis
    volumes:
      - ./config:/home/application/app/config
    networks:
      - eosio-contract-api
  eosio-contract-api-server:
    container_name: eosio-contract-api-server
    build: .
    command: yarn run start:server
    restart: on-failure
    ports:
      - "9000:9000"
    depends_on:
      - eosio-contract-api-postgres
      - eosio-contract-api-redis
    volumes:
      - ./config:/home/application/app/config
    networks:
      - eosio-contract-api
  eosio-contract-api-redis:
    container_name: eosio-contract-api-redis
    image: redis:5-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - /mnt/dn/redis:/data
    networks:
      - eosio-contract-api
  eosio-contract-api-postgres:
    container_name: eosio-contract-api-postgres
    image: postgres:14.9
    restart: on-failure
    shm_size: '64gb'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SecretPgPw78&&00}
      POSTGRES_DB: ${POSTGRES_DB:-api-wax-mainnet-atomic-1}
    ports:
      - "5432:5432"
    volumes:
      - /mnt/dn/postgresql:/var/lib/postgresql/data
      - /tmp/atomic.dump:/tmp/atomic.dump
    networks:
      - eosio-contract-api
networks:
  eosio-contract-api:
    driver: bridge
